<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_open_door_tests.TestAccessManager-20210517124419" tests="5" file="test_open_door_tests.py" time="0.014" timestamp="2021-05-17T12:44:20" failures="2" errors="0" skipped="0">
	<testcase classname="test_open_door_tests.TestAccessManager" name="test_open_door_bad_key_is_expired" time="0.002" timestamp="2021-05-17T12:44:20"/>
	<testcase classname="test_open_door_tests.TestAccessManager" name="test_open_door_bad_key_is_not_found" time="0.002" timestamp="2021-05-17T12:44:20"/>
	<testcase classname="test_open_door_tests.TestAccessManager" name="test_open_door_bad_key_regex" time="0.001" timestamp="2021-05-17T12:44:20"/>
	<testcase classname="test_open_door_tests.TestAccessManager" name="test_open_door_good" time="0.005" timestamp="2021-05-17T12:44:20">
		<failure type="AssertionError" message="True != 'Puerta abierta'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\adrianpr\pycharmprojects\g81.t10.fp\src\unittest\python\test_open_door_tests.py", line 57, in test_open_door_good
    self.assertEqual(True, result)
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: True != 'Puerta abierta'
]]></failure>
	</testcase>
	<testcase classname="test_open_door_tests.TestAccessManager" name="test_open_door_resident" time="0.004" timestamp="2021-05-17T12:44:20">
		<failure type="AssertionError" message="True != 'Puerta abierta'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\adrianpr\pycharmprojects\g81.t10.fp\src\unittest\python\test_open_door_tests.py", line 64, in test_open_door_resident
    self.assertEqual(True, result)
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\AdrianPR\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: True != 'Puerta abierta'
]]></failure>
	</testcase>
</testsuite>
